### PR TITLE
Added Enum macros for GUI

### PR DESCRIPTION
**Pull request by tsadowski**
Hi, I wrote a Rust and Slint GUI using your library. I had to add some macros to enums and it would be great if this could be merged.

### CODE REVIEW

**Comment by soulsource** [comment]
Hi! Thanks for the PR!

I'm a bit unsure about the new dependencies it adds, but I think it's fine.
I'll have a closer look and probably merge it later today, once I'm done with work.

**Comment by soulsource** [comment]
Okay, I had a look and thought a bit about it.
I'll merge this now, and add a feature-gate later, that will make the strum dependency optional.

**Comment by tsadowski** [comment]
Thank you!

Am Mittwoch, dem 22.05.2024 um 09:10 -0700 schrieb Andreas Grois:

**Comment by soulsource** [comment]
I've made a small edit that makes the dependency on strum optional. It's now behind the `strum` feature flag.

**Comment by tsadowski** [comment]
Thanks for the info. I updated my Cargo.toml.

Am Samstag, dem 01.06.2024 um 13:00 -0700 schrieb Andreas Grois:

**Pull request merged**
